
export const ROUTES_CONST = {
  login: "/",
  dashboard: "/dashboard",
  dashboardPage: "/dashboardPage",
  masterdownlineList: "/master-downline-list",
  GlobalSettings: "/GlobalSettings",
  CreateNewMatch: "/CreateNewMatch",
  CreateManualMatch: "/CreateManualMatch",
  AllMatches: "/AllMatches",
  userDownLineList: "/user-downline-list",
  TransferMatchCoins: "/TransferMatchCoins",
  PendingLiability: "/PendingLiability",
  CoinLog: "/CoinLog",
  ManageBets : '/manageBets',
  MatchOddsBets: "/MatchOddsBets",
  MatchOddsRevertBets: "/MatchOddsRevertBets",
  TossMatchList: "/TossMatchList",
  MultipleSession: "/MultipleSession",
  AllSessionList: "/AllSessionList",
  AllSessionListRevert: "/AllSessionListRevert",
  Banner: "/Banner",
  SessionPreBook: "/SessionPreBook",
  SessionResult: "/SessionResult",
  ProfitLoss: "/ProfitLoss",
  EventProfitLoss: "/EventProfitLoss",
  BetList: "/BetList",
  MyAccount: "/MyAccount",
  userbanking: "user-banking",
  masterbanking: "/master-banking",
  passwordHistory: "/password-history",
  restoreUser: "/restore-user",
  marketAnalysis: '/market-analysis',
  changePassword: "/changePassword" ,
  SportsandLossEvents: "/sportsandlossevents",
  ProfitLossUser: '/profit-loss-user',
  BetHistory :"/bet-history"  ,
  commission : "/commission",
  CasinoSettings : "/casinoSettings",
  CasinoGamesList : "/casino-games-list",
  liabilty : '/liability',
  TossResult : '/toss-result',
  PendingMarket : '/pending-market',
  BookmakerBet : '/bookmakerbets',
  BookmakerRevertBet : '/bookmaker-revert-bets',
  CasinoSportList : '/casino-sport-list',
  tossBetList: '/toss-bet',
  tossBetRevertList : '/toss-revert-bets'
};
